DROP DATABASE RIPITI;
CREATE DATABASE RIPITI AUTOMATIC STORAGE YES  ON /Baze USING CODESET UTF-8 TERRITORY SP COLLATE USING SYSTEM PAGESIZE 32768;
UPDATE DB CFG FOR RIPITI USING logprimary 10 logsecond 10 logfilsiz 80000;
